import { writeFileSync } from "node:fs";
import { loadCatalog, loadStars, loadTaxonomy } from "./lib/catalog.ts";
import { githubRepoKey, parseGithubRepo } from "./lib/github.ts";
import { README_MD } from "./lib/paths.ts";
import { sortSkills } from "./lib/rank.ts";
import type { Skill, StarsCache, Taxonomy } from "./lib/types.ts";

function displaySummary(text: string): string {
  const one = text.replace(/\s+/g, " ").trim();
  if (one.length <= 120) return one;
  return `${one.slice(0, 117)}…`;
}

function starBadge(repoUrl: string): string {
  const parsed = parseGithubRepo(repoUrl);
  if (!parsed) return "";
  const badge = `https://badgen.net/github/stars/${parsed.owner}/${parsed.repo}`;
  return ` [![GitHub Stars](${badge})](${repoUrl})`;
}

function skillLine(skill: Skill): string {
  const badge = starBadge(skill.source.repo);
  return `- [${skill.name}](skills/${skill.id}/)${badge} — ${displaySummary(skill.summary)}`;
}

function sectionFor(
  title: string,
  taxonomy: Record<string, { label: string }>,
  skills: Skill[],
  pick: (skill: Skill) => string[],
  stars: StarsCache,
): string {
  const chunks: string[] = [`## ${title}`, ""];
  let any = false;
  for (const [key, meta] of Object.entries(taxonomy)) {
    const matched = sortSkills(
      skills.filter((skill) => pick(skill).includes(key)),
      stars,
    );
    if (matched.length === 0) continue;
    any = true;
    chunks.push(`### ${meta.label}`, "");
    for (const skill of matched) chunks.push(skillLine(skill));
    chunks.push("");
  }
  if (!any) {
    chunks.push("_暂无。_");
    chunks.push("");
  }
  return chunks.join("\n");
}

function uniqueRepos(skills: Skill[]): string[] {
  return [...new Set(skills.map((skill) => skill.source.repo))].sort();
}

export function renderReadme(): string {
  const catalog = loadCatalog();
  const taxonomy = loadTaxonomy();
  const stars = loadStars();
  const skills = catalog.skills.filter((skill) => skill.status === "active");
  const fetchedAt = Object.values(stars)
    .map((item) => item.fetched_at)
    .sort()
    .at(-1);

  const toc = [
    "- [按平台](#按平台)",
    "- [按创作类型](#按创作类型)",
    "- [按创作形式](#按创作形式)",
    "- [安装](#安装)",
    "- [收录与同步](#收录与同步)",
    "- [上游归属](#上游归属)",
  ].join("\n");

  const repoList = uniqueRepos(skills)
    .map((repo) => `- ${repo}`)
    .join("\n");

  return `# Awesome Creator Skills

<!-- Generated by scripts/generate-readme.ts; edit catalog/*.yaml instead. -->

搜集全网**创作向** Agent Skills 的可安装镜像库：覆盖微信公众号、小红书、YouTube、X 等平台，以及文章、图片、图文、视频等类型。

本仓库不只放链接。技能会拷贝到 [\`skills/\`](skills/)，你可以直接：

\`\`\`bash
npx skills add BigPengSays/awesome-creator-skills --skill <skill-id>
\`\`\`

镜像版权仍归原作者。GitHub 来源用 [badgen](https://badgen.net) star 徽章展示源仓库实时 star；分类内按 **star × 时间衰减** 排序（约 21 天半衰期：1k star 且 7 天内有提交，会排在 4k star 但已两个月未更新的前面）。

${toc}

${sectionFor("按平台", taxonomy.platforms, skills, (skill) => skill.platforms, stars)}
${sectionFor("按创作类型", taxonomy.content_types, skills, (skill) => skill.content_types, stars)}
${sectionFor("按创作形式", taxonomy.formats, skills, (skill) => skill.formats, stars)}
## 安装

先浏览上面的分类，记下 skill id（链接中的目录名），然后：

\`\`\`bash
npx skills add BigPengSays/awesome-creator-skills --skill baoyu-post-to-wechat
\`\`\`

安装全部技能：

\`\`\`bash
npx skills add BigPengSays/awesome-creator-skills --skill '*'
\`\`\`

## 收录与同步

- 新技能不会自动入库。发现脚本会发到飞书，并开 GitHub Issue；确认后再 vendor。
- 来自 Git 的条目默认会定期从上游同步，变更以 Pull Request 提交。
- 分类标签、收录标准见 [CONTRIBUTING.md](CONTRIBUTING.md)。
- 目录由 \`catalog/skills.yaml\` + \`catalog/stars.yaml\` 生成，请勿手改本 README 的分类列表。
${fetchedAt ? `\n源仓库 star 缓存更新于 \`${fetchedAt}\`。\n` : ""}
## 上游归属

Vendored skills remain the work of their original authors. See each skill's \`SOURCE.md\` and:

${repoList || "_暂无。_"}

This repository's own scripts and catalog are MIT licensed. Third-party skills keep their upstream licenses.
`;
}

export async function generateReadme(): Promise<void> {
  writeFileSync(README_MD, renderReadme());
  console.log("Wrote README.md");
}

const isDirect = process.argv[1]?.endsWith("generate-readme.ts");
if (isDirect) {
  generateReadme().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
