import { writeFileSync } from "node:fs";
import { loadCatalog, loadStars, loadTaxonomy } from "./lib/catalog.ts";
import { parseGithubRepo } from "./lib/github.ts";
import { README_MD } from "./lib/paths.ts";
import { sortSkills } from "./lib/rank.ts";
import { sourceAttribution, type Skill, type StarsCache, type Taxonomy } from "./lib/types.ts";

function displaySummary(text: string): string {
  const one = text.replace(/\s+/g, " ").trim();
  if (one.length <= 220) return one;
  return `${one.slice(0, 217)}…`;
}

function sourceSkillUrl(skill: Skill): string {
  if (skill.source.type === "url") return skill.source.url;
  const clean = skill.source.path.replace(/^\/+|\/+$/g, "");
  if (!clean || clean === ".") return skill.source.repo;
  const encodedPath = clean.split("/").map(encodeURIComponent).join("/");
  return `${skill.source.repo}/tree/${encodeURIComponent(skill.source.ref)}/${encodedPath}`;
}

function starBadge(repoUrl: string): string {
  const parsed = parseGithubRepo(repoUrl);
  if (!parsed) return "";
  const badge = `https://badgen.net/github/stars/${parsed.owner}/${parsed.repo}`;
  return ` [![GitHub Stars](${badge})](${repoUrl})`;
}

function skillLine(skill: Skill): string {
  const badge = skill.source.type === "git" ? starBadge(skill.source.repo) : "";
  return `- [${skill.name}](${sourceSkillUrl(skill)})${badge} — ${displaySummary(skill.summary)} · [镜像](skills/${skill.id}/)`;
}

function sectionFor(
  title: string,
  taxonomy: Record<string, { label: string }>,
  skills: Skill[],
  pick: (skill: Skill) => string[],
  stars: StarsCache,
): string {
  const chunks: string[] = [`## ${title}`, ""];
  let any = false;
  for (const [key, meta] of Object.entries(taxonomy)) {
    const matched = sortSkills(
      skills.filter((skill) => pick(skill).includes(key)),
      stars,
    );
    if (matched.length === 0) continue;
    any = true;
    chunks.push(`#### ${meta.label}`, "");
    for (const skill of matched) chunks.push(skillLine(skill));
    chunks.push("");
  }
  if (!any) {
    chunks.push("_暂无。_");
    chunks.push("");
  }
  return chunks.join("\n");
}

function uniqueRepos(skills: Skill[]): string[] {
  return [...new Set(skills.map((skill) => sourceAttribution(skill.source)))].sort();
}

function coverageLine(skills: Skill[], taxonomy: Taxonomy): string {
  const platformKeys = new Set(skills.flatMap((skill) => skill.platforms));
  const typeKeys = new Set(skills.flatMap((skill) => skill.content_types));
  const platforms = Object.entries(taxonomy.platforms)
    .filter(([key]) => platformKeys.has(key) && key !== "generic")
    .map(([, meta]) => meta.label);
  const types = Object.entries(taxonomy.content_types)
    .filter(([key]) => typeKeys.has(key))
    .map(([, meta]) => meta.label);
  const platformPart = platforms.length
    ? `覆盖${platforms.join("、")}`
    : "按发布渠道整理";
  const typePart = types.length
    ? `内容形态包括${types.join("、")}。`
    : "";
  return `当前精选 **${skills.length}** 项，${platformPart}。${typePart ? `\n\n${typePart}` : ""}`;
}

export function renderReadme(): string {
  const catalog = loadCatalog();
  const taxonomy = loadTaxonomy();
  const stars = loadStars();
  const skills = catalog.skills.filter((skill) => skill.status === "active");

  const repoList = uniqueRepos(skills)
    .map((repo) => `- ${repo}`)
    .join("\n");

  return `<!-- Generated by scripts/generate-readme.ts. Do not edit by hand. -->

# 创作技能合集

面向内容创作者的 **精选 Agent Skills** 目录。只收录与内容生产直接相关、可一键安装到 Cursor、Claude Code 等环境的技能，按发布渠道与内容形态整理。

${coverageLine(skills, taxonomy)}

名称指向源技能原文，star 徽章指向源仓库，\`镜像\` 为本目录中的可安装拷贝。

\`\`\`bash
npx skills add BigPengSays/awesome-creator-skills --skill <skill-id>
\`\`\`

${sectionFor("按平台", taxonomy.platforms, skills, (skill) => skill.platforms, stars)}
${sectionFor("按创作类型", taxonomy.content_types, skills, (skill) => skill.content_types, stars)}
${sectionFor("按创作形式", taxonomy.formats, skills, (skill) => skill.formats, stars)}
## 安装

安装单个技能：

\`\`\`bash
npx skills add BigPengSays/awesome-creator-skills --skill baoyu-post-to-wechat
\`\`\`

安装全部技能：

\`\`\`bash
npx skills add BigPengSays/awesome-creator-skills --skill '*'
\`\`\`

## 版权归属

技能版权仍归原作者。本仓库目录与脚本采用 MIT 许可，各技能保留其上游许可证。详见各技能目录中的 \`SOURCE.md\`，以及：

${repoList || "_暂无。_"}
`;
}

export async function generateReadme(): Promise<void> {
  writeFileSync(README_MD, renderReadme());
  console.log("Wrote README.md");
}

const isDirect = process.argv[1]?.endsWith("generate-readme.ts");
if (isDirect) {
  generateReadme().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
